package com.hbm.nucleartech.damagesource;

import com.hbm.nucleartech.HBM;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.damagesource.DamageType;

public interface HbmDamageTypes {

    ResourceKey<DamageType> BLAST = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "blast"));
    ResourceKey<DamageType> NUCLEAR_BLAST = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "nuclear_blast"));
    ResourceKey<DamageType> MUD_POISONING = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "mud_poisoning"));
    ResourceKey<DamageType> ACID = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "acid"));
    ResourceKey<DamageType> EUTHANIZED_SELF = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "euthanized_self"));
    ResourceKey<DamageType> EUTHANIZED_SELF_2 = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "euthanized_self_2"));
    ResourceKey<DamageType> TAU_BLAST = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "tau_blast"));
    ResourceKey<DamageType> RADIATION = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "radiation"));
    ResourceKey<DamageType> DIGAMMA = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "digamma"));
    ResourceKey<DamageType> SUICIDE = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "suicide"));
    ResourceKey<DamageType> TELEPORTER = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "teleporter"));
    ResourceKey<DamageType> CHEATER = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "cheater"));
    ResourceKey<DamageType> RUBBLE = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "rubble"));
    ResourceKey<DamageType> SHRAPNEL = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "shrapnel"));
    ResourceKey<DamageType> BLACK_HOLE = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "black_hole"));
    ResourceKey<DamageType> BLENDER = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "blender"));
    ResourceKey<DamageType> METEORITE = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "meteorite"));
    ResourceKey<DamageType> BOXCAR = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "boxcar"));
    ResourceKey<DamageType> BOAT = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "boat"));
    ResourceKey<DamageType> BUILDING = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "building"));
    ResourceKey<DamageType> TAINT = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "taint"));
    ResourceKey<DamageType> AMS = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "ams"));
    ResourceKey<DamageType> AMS_CORE = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "ams_core"));
    ResourceKey<DamageType> BROADCAST = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "broadcast"));
    ResourceKey<DamageType> BANG = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "bang"));
    ResourceKey<DamageType> PC = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "pc"));
    ResourceKey<DamageType> CLOUD = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "cloud"));
    ResourceKey<DamageType> LEAD = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "lead"));
    ResourceKey<DamageType> ENERVATION = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "enervation"));
    ResourceKey<DamageType> ELECTRICITY = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "electricity"));
    ResourceKey<DamageType> EXHAUST = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "exhaust"));
    ResourceKey<DamageType> SPIKES = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "spikes"));
    ResourceKey<DamageType> LUNAR = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "lunar"));
    ResourceKey<DamageType> MONOXIDE = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "monoxide"));
    ResourceKey<DamageType> ASBESTOS = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "asbestos"));
    ResourceKey<DamageType> BLACKLUNG = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "blacklung"));
    ResourceKey<DamageType> MKU = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "mku"));
    ResourceKey<DamageType> VACUUM = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "vacuum"));
    ResourceKey<DamageType> OVERDOSE = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "overdose"));
    ResourceKey<DamageType> MICROWAVE = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "microwave"));
    ResourceKey<DamageType> NITAN = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "nitan"));
    ResourceKey<DamageType> REVOLVER_BULLET = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "revolver_bullet"));
    ResourceKey<DamageType> CHOPPER_BULLET = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "chopper_bullet"));
    ResourceKey<DamageType> TAU = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "tau"));
    ResourceKey<DamageType> CMB = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "cmb"));
    ResourceKey<DamageType> SUB_ATOMIC = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "sub_atomic"));
    ResourceKey<DamageType> EUTHANIZED = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "euthanized"));
    ResourceKey<DamageType> ELECTRIFIED = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "electrified"));
    ResourceKey<DamageType> FLAMETHROWER = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "flamethrower"));
    ResourceKey<DamageType> PLASMA = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "plasma"));
    ResourceKey<DamageType> ICE = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "ice"));
    ResourceKey<DamageType> LASER = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "laser"));
    ResourceKey<DamageType> BOIL = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "boil"));
    ResourceKey<DamageType> ACID_PLAYER = ResourceKey.create(Registries.DAMAGE_TYPE, ResourceLocation.fromNamespaceAndPath(HBM.MOD_ID, "acid_player"));
}
